<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 12px; line-height: 1.4; }
        h1 { margin-bottom: 20px; font-size: 18px; color: #333; }
        .header-info { margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #eee; }
        .header-info p { margin: 5px 0; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f5f5f5; font-weight: bold; text-align: left; padding: 10px 8px; border-bottom: 2px solid #ddd; font-size: 11px; text-transform: uppercase; color: #555; }
        td { padding: 8px; border-bottom: 1px solid #ddd; text-align: left; vertical-align: top; }
        tr:nth-child(even) { background-color: #fafafa; }
        tr:hover { background-color: #f0f0f0; }
        .role-badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .role-admin { background-color: #e74c3c; color: white; }
        .role-staff { background-color: #3498db; color: white; }
        .role-doctor { background-color: #2ecc71; color: white; }
        .counter-tag { display: inline-block; background: #e9ecef; padding: 2px 6px; margin: 2px; border-radius: 3px; font-size: 10px; }
        .footer { margin-top: 30px; font-size: 10px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
        .empty-state { text-align: center; color: #888; padding: 30px !important; }
    </style>
</head>
<body>
    <div class="header-info">
        <h1>{{ $title }}</h1>
        <p><strong>Generated on:</strong> {{ $date }}</p>
        <p><strong>Total Records:</strong> {{ $users->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Department</th>
                <th>Counter Assigned</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $index => $user)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    @php
                        $roleClass = match($user->role->name ?? '') {
                            'Admin' => 'role-admin',
                            'Hospital Staff' => 'role-staff',
                            'Doctor' => 'role-doctor',
                            default => 'role-staff'
                        };
                    @endphp
                    <span class="role-badge {{ $roleClass }}">{{ $user->role->name ?? 'N/A' }}</span>
                </td>
                <td>{{ $user->department->name ?? 'Not assigned' }}</td>
                <td>
                    @if($user->assignedCounters && $user->assignedCounters->count() > 0)
                        @foreach($user->assignedCounters as $counter)
                            <span class="counter-tag">{{ $counter->name }}</span>
                        @endforeach
                    @else
                        None
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="empty-state">No records found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by XYZ Hospital Queue Management System · Confidential
    </div>
</body>
</html>
